### ISSUE TITLE
Add support for ALPN

### ISSUE THREAD

**Issue by rforbes** [openssl-net/openssl-net#14]
I was using this project as a template https://github.com/MSOpenTech/http2-katana/ but I noticed the version of ManagedOpenSsl is older than the one here.  I tried to update to this current version  but there seem to be a lot of changes, especially in SslStream.  For instance, AlpnSelectedProtocol is no longer in SslStream.  Is there any documentation on these changes?

**Comment by flaub** [comment]
Hey rooster, I had no idea that MS forked this project. They must have taken a snapshot from around 2013, some things were added since then. It'd be nice if they would have contributed to this project instead.

A changelog can be found here: https://github.com/openssl-net/openssl-net/blob/master/CHANGES

I'll poke the maintainer over at http2-katana and see if they would like to send some PRs for their updates.

**Comment by flaub** [comment]
Let's see if MSOpenTech/http2-katana#72 goes anywhere.

**Comment by flaub** [comment]
After a cursory investigation, it looks like this was the initial commit: MSOpenTech/http2-katana@116cb5413cdc08202355aeea40f2accb09f097a6

Since that time, it appears the ALPN and some additional TLS improvements were made.

**Comment by rforbes** [comment]
Ahh. I had a feeling. My ultimate goal is to make a publisher so I can
start fuzzing http2. This requires establishing the tunnel with Ssl using
alpn. Should I just be using the Microsoft one?

**Comment by flaub** [comment]
Not sure, but I know we have plans to implement an HTTP/2 pit in the near future...

**Comment by rforbes** [comment]
Would still need the publisher as sspi doesn't support alpn.

**Comment by adamcaudill** [comment]
@rforbes Thanks for bringing this to our attention - this is a good opportunity to merge in some useful changes.

**Comment by flaub** [comment]
I'd like to write some tests before we close this.
